version: '2'

services:
  tailscale:
    # where <arch> is one of aarch64, armv7hf or amd64
    image: bh.cr/gh_klutchell/tailscale-aarch64
    network_mode: host
    restart: on-failure
    volumes:
      - ts-state:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/

  owrx:
    image: 'slechev/openwebrxplus-softmbe:latest'
    container_name: owrx-mbe
    restart: unless-stopped
    ports:
      - '8073:8073'
    environment:
      TZ: Europe/London
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - openwebrxetc:/etc/openwebrx
      - openwebrxvar:/var/lib/openwebrx
      - openwebrxplugins:/usr/lib/python3/dist-packages/htdocs/plugins
    # mount /tmp in memory, for RPi devices, to avoid SD card wear and make dump1090 work faster
    tmpfs:
      - /tmp:mode=1777

volumes:
  watchdog-log:
  ts-state: {}
  openwebrxetc:
  openwebrxvar:
  openwebrxplugins:
