name: BalenaCloud Fleet Deploy (Production)

on:
  workflow_dispatch:
  push:

permissions: 
  contents: write

env:
  fleet: gh_goshawk22/rockpi-server
  
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Balena Deploy
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_API_TOKEN}}
          balena_cli_commands: "deploy ${{ env.fleet }} --debug --nocache --build"
          balena_cli_version: 13.7.1

