name: BalenaCloud Fleet Deploy (Production)

on:
  workflow_dispatch:
  push:

jobs:
  balena-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: balena CLI Action
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            push gh_goshawk22/rockpi-server;
          balena_cli_version: 17.1.1
